### ISSUE TITLE
第一周作业

### ISSUE THREAD

**Issue by yuanxiao1234** [algorithm020/algorithm020#3]
#学号:G20200343170061
#姓名:袁潇
#小组:3组
#语言:Golang
#作业链接&总结链接:https://github.com/yuanxiao1234/algorithm020/tree/main/Week1

**Comment by xudongstorm** [comment]
#学号:G20200343170035
#姓名:dong.
#小组:4组
#语言:java
#作业链接&总结链接:https://github.com/xudongstorm/algorithm020/tree/main/Week1
